name: 编译 dart_simple_live
# 👇 关键：同时支持 push 和手动触发
on:
  push:
    branches: [ main ]
  workflow_dispatch:   # 👈 加这一行！就会出现 Run workflow 按钮

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装 Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: stable

      - name: 安装项目依赖
        run: |
          cd simple_live_app
          flutter pub get

      - name: 编译 Android APK
        run: |
          cd simple_live_app
          flutter build apk --release

      - name: 上传 APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: simple_live_app/build/app/outputs/flutter-apk/app-release.apk
